# Diff Configuration.

######################### Global config #########################

# how many goroutines are created to check data
check-thread-count = 4

# set false if just want compare data by checksum, will skip select data when checksum is not equal.
# set true if want compare all different rows, will slow down the total compare time.
export-fix-sql = true

# ignore check table's data
check-struct-only = false


######################### Databases config #########################
[data-sources]
[data-sources.mysql1]
    host = "127.0.0.1"
    port = 3306
    user = "root"
    password = ""
    # mysql doesn't has snapshot config

[data-sources.tidb0]
    host = "127.0.0.1"
    port = 4000
    user = "root"
    password = ""
    # remove comment if use tidb's snapshot data
    # snapshot = "2016-10-08 16:45:26"
    # snapshot = "386902609362944000"

######################### Task config #########################
# Required
[task]
    # 1 fix sql: fix-target-TIDB1.sql
    # 2 log: sync-diff.log
    # 3 summary: summary.txt
    # 4 checkpoint: a dir
    output-dir = "/tmp/output/config_conflict"

    source-instances = ["mysql1"]

    target-instance = "tidb0"

    # tables need to check. *Include `schema` and `table`. Use `.` to split*
    target-check-tables = ["schema*.table*", "!c.*", "test2.t2"]

    # extra table config
    target-configs= ["config1", "config2"]

# Optional
[table-configs]
[table-configs.config1]
# tables need to use this specified config.
# if use this config. target-tables should be a subset of #target-check-tables
target-tables = ["schema*.table*", "test2.t2"]
range = "age > 10 AND age < 20"
index-fields = [""]
ignore-columns = ["",""]
chunk-size = 0
collation = ""

[table-configs.config2]
# conflict config with config1
target-tables = ["schema*.table*", "test2.t2"]
range = "age > 10 AND age < 20"
index-fields = [""]
ignore-columns = ["",""]
chunk-size = 0
collation = ""
