version: "2.3"
services:
  server-master:
    image: dataflow:test
    volumes:
      - ./config/master.toml:/config.toml
    command:
      - "/tiflow"
      - "master"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--addr=0.0.0.0:10240"
      - "--advertise-addr=server-master:10240"
    ports:
      - "10240:10240"
    depends_on:
      "etcd-standalone":
        condition: service_started
      "mysql-standalone":
        condition: service_healthy
  server-executor:
    image: dataflow:test
    volumes:
      - ./config/executor.toml:/config.toml
    command:
      - "/tiflow"
      - "executor"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--join=server-master:10240"
      - "--addr=0.0.0.0:10241"
      - "--advertise-addr=server-executor:10241"
    ports:
      - "10241:10241"
    depends_on:
      - "server-master"
    restart: "on-failure"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=UTC
  etcd-standalone:
    image: quay.io/coreos/etcd
    container_name: etcd-standalone
    command:
      - "etcd"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://etcd-standalone:2379"
    ports:
      - "12479:2379"
  mysql-standalone:
    image: mysql:5.7
    container_name: mysql_standalone
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - './config/mysql_meta.cnf:/etc/my.cnf'
    ports:
      - "3336:3306"
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -P3306 -uroot -p123456"
      interval: 10s
      timeout: 600s
      retries: 60
