version: "2.3"
services:
  server-master-0:
    image: dataflow:test
    container_name: 3m3e-server-master-0
    ports:
      - "10245:10240"
    volumes:
      - ./config/master.toml:/config.toml
    command:
      - "/tiflow"
      - "master"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--addr=0.0.0.0:10240"
      - "--advertise-addr=server-master-0:10240"
    depends_on:
      "etcd-standalone":
        condition: service_started
      "mysql-standalone":
        condition: service_healthy
  server-master-1:
    image: dataflow:test
    container_name: 3m3e-server-master-1
    ports:
      - "10246:10240"
    volumes:
      - ./config/master.toml:/config.toml
    command:
      - "/tiflow"
      - "master"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--addr=0.0.0.0:10240"
      - "--advertise-addr=server-master-1:10240"
    depends_on:
      "etcd-standalone":
        condition: service_started
      "mysql-standalone":
        condition: service_healthy
  server-master-2:
    image: dataflow:test
    container_name: 3m3e-server-master-2
    ports:
      - "10247:10240"
    volumes:
      - ./config/master.toml:/config.toml
    command:
      - "/tiflow"
      - "master"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--addr=0.0.0.0:10240"
      - "--advertise-addr=server-master-2:10240"
    depends_on:
      "etcd-standalone":
        condition: service_started
      "mysql-standalone":
        condition: service_healthy
  server-executor-0:
    image: dataflow:test
    container_name: 3m3e-server-executor-0
    ports:
      - "11241:10241"
    volumes:
      - ./config/executor.toml:/config.toml
    command:
      - "/tiflow"
      - "executor"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--join=server-master-0:10240,server-master-1:10240,server-master-2:10240"
      - "--addr=0.0.0.0:10241"
      - "--advertise-addr=server-executor-0:10241"
    depends_on:
      - "server-master-0"
      - "server-master-2"
      - "server-master-1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  server-executor-1:
    image: dataflow:test
    container_name: 3m3e-server-executor-1
    ports:
      - "11242:10241"
    volumes:
      - ./config/executor.toml:/config.toml
    command:
      - "/tiflow"
      - "executor"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--join=server-master-0:10240,server-master-1:10240,server-master-2:10240"
      - "--addr=0.0.0.0:10241"
      - "--advertise-addr=server-executor-1:10241"
    depends_on:
      - "server-master-0"
      - "server-master-2"
      - "server-master-1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  server-executor-2:
    image: dataflow:test
    container_name: 3m3e-server-executor-2
    ports:
      - "11243:10241"
    volumes:
      - ./config/executor.toml:/config.toml
    command:
      - "/tiflow"
      - "executor"
      - "--config=/config.toml"
      - "--log-level=debug"
      - "--join=server-master-0:10240,server-master-1:10240,server-master-2:10240"
      - "--addr=0.0.0.0:10241"
      - "--advertise-addr=server-executor-2:10241"
    depends_on:
      - "server-master-0"
      - "server-master-2"
      - "server-master-1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  etcd-standalone:
    image: quay.io/coreos/etcd
    container_name: 3m3e-etcd-standalone
    command:
      - "etcd"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://etcd-standalone:2379"
    ports:
      - "12479:2379"
  mysql-standalone:
    image: mysql:5.7
    container_name: 3m3e-mysql-standalone
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - './config/mysql_meta.cnf:/etc/my.cnf'
    ports:
      - "3336:3306"
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -P3306 -uroot -p123456"
      interval: 10s
      timeout: 600s
      retries: 60
