version: '3.5'

services:
  storage_integration_test:
    build:
      context: ../../../
      dockerfile: ./deployments/ticdc/docker/integration-test.Dockerfile
      args:
        BRANCH: ${BRANCH}
        COMMUNITY: ${COMMUNITY}
        VERSION: ${VERSION} 
        OS: ${SYS}
        ARCH: ${ARCH}
    command:
      - bash
      - -c
      - make integration_test_storage CASE="${CASE}" START_AT="${START_AT}"  & tail -f /dev/null
    volumes:
      - ./logs/tidb_cdc_test:/tmp/tidb_cdc_test
      - ../../../tests:/go/src/github.com/pingcap/tiflow/tests
