version: '2.1'

services:
  mysql_integration_test:
    build:
      context: ../../../
      dockerfile: ./deployments/ticdc/docker/integration-test.Dockerfile
    command:
      - bash
      - -c
      - make integration_test_mysql CASE=cdclog_s3 & tail -f /dev/null
    volumes:
      - ./logs/tidb_cdc_test:/tmp/tidb_cdc_test
