apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-cdc
  labels:
    app: pod-failure-cdc
spec:
  action: pod-failure
  mode: one
  duration: "20s"
  selector:
    pods:
      playground:
        - cdc-0
        - upstream-tikv-0
        - upstream-pd-0
        - downstream-tidb-0
  scheduler:
    cron: "@every 2m"
