apiVersion: v1
kind: Service
metadata:
  name: cdc
  labels:
    app: cdc
spec:
  ports:
    - name: cdc
      port: 8300
      targetPort: 8300
  selector:
    app: cdc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdc
  labels:
    app: cdc
spec:
  selector:
    matchLabels:
      app: cdc
  serviceName: cdc
  replicas: 1
  template:
    metadata:
      labels:
        app: cdc
    spec:
      containers:
        - name: cdc
          image: cdc:chaos
          imagePullPolicy: IfNotPresent # build this image in GitHub action workflow, make sure use local image
          volumeMounts:
            - mountPath: /data
              name: cdc
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8300
              name: cdc
          command:
            - "/cdc"
            - "server"
            - "--pd=http://upstream-pd.playground.svc:2379"
            - "--log-file=/var/log/$(MY_POD_NAME).log"
            - "--data-dir=/data"
  volumeClaimTemplates:
    - metadata:
        name: cdc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
