# IT IS NOT SUITABLE FOR PRODUCTION USE.
# This YAML describes a basic TiDB cluster with minimum resource requirements,
# which should be able to run in any Kubernetes cluster with storage support.
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: upstream
spec:
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  imagePullPolicy: Always
  discovery: {}
  pd:
    baseImage: pingcap/pd
    version: nightly
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "1Gi"
    config:
      log:
        file:
          filename: /var/log/pdlog/pd.log
        level: "warn"
    storageVolumes:
      - name: log
        storageSize: "1Gi"
        mountPath: "/var/log/pdlog"
  tikv:
    baseImage: pingcap/tikv
    version: nightly
    replicas: 1
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    # storageClassName: local-storage
    requests:
      storage: "3Gi"
    config:
      storage:
        # In basic examples, we set this to avoid using too much storage.
        reserve-space: "0MB"
      rocksdb:
        # In basic examples, we set this to avoid the following error in some Kubernetes clusters:
        # "the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"
        max-open-files: 4096
      raftdb:
        max-open-files: 4096
    storageVolumes:
      - name: log
        storageSize: "1Gi"
        mountPath: "/var/log/kvlog"
  tidb:
    baseImage: pingcap/tidb
    version: nightly
    replicas: 1
    service:
      type: ClusterIP
    config:
      log:
        file:
          filename: /var/log/tidblog/tidb.log
        level: "warn"
    storageVolumes:
      - name: log
        storageSize: "1Gi"
        mountPath: "/var/log/tidblog"
