apiVersion: batch/v1
kind: Job
metadata:
  name: bank-workload
spec:
  template:
    spec:
      containers:
        - name: bank-workload
          image: bank-workload # build this image in GitHub action workflow
          imagePullPolicy: IfNotPresent
          command:
            - "/bank"
            - "--upstream=root@tcp(upstream-tidb.playground.svc:4000)/bank"
            - "--downstream=root@tcp(downstream-tidb.playground.svc:4000)/bank"
            - "--test-round=2000"
      restartPolicy: Never
  backoffLimit: 0 # fail immediately
