[etcd]
data-dir = "/data/etcd"

[frame-metastore-conf]
endpoints = ["metastore-framework:13306"]
auth.user = "root"
auth.passwd = ""

[business-metastore-conf]
endpoints = ["metastore-business:12479"]
