apiVersion: v1
kind: Service
metadata:
  name: metastore-framework
  labels:
    app: metastore-framework
spec:
  ports:
    - name: port-mysql # note the name is no more than 15 characters
      port: 13306
      targetPort: 3306
  selector:
    app: metastore-framework

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metastore-framework-mysql
  labels:
    app: metastore-framework
spec:
  selector:
    matchLabels:
      app: metastore-framework
  serviceName: metastore-framework
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: metastore-framework
    spec:
      containers:
        - name: metastore-framework-mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: metastore-framework-mysql
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          ports:
            - containerPort: 3306
              name: port-mysql
          args:
            - "--server-id=1"
  volumeClaimTemplates:
    - metadata:
        name: metastore-framework-mysql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi


---
apiVersion: v1
kind: Service
metadata:
  name: metastore-business
  labels:
    app: metastore-business
spec:
  ports:
    - name: port-etcd # note the name is no more than 15 characters
      port: 12479
      targetPort: 2479
  selector:
    app: metastore-business


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metastore-business-etcd
  labels:
    app: metastore-business
spec:
  selector:
    matchLabels:
      app: metastore-business
  serviceName: metastore-business
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: metastore-business
    spec:
      containers:
        - name: metastore-business-etcd
          image: quay.io/coreos/etcd:v3.5.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2479
              name: port-etcd
          command:
            - "etcd"
          args:
            - "--name=metastore-business-etcd"
            - "--advertise-client-urls=http://0.0.0.0:2479"
            - "--listen-client-urls=http://0.0.0.0:2479"
            - "--listen-peer-urls=http://127.0.0.1:2480"
            - "--initial-advertise-peer-urls=http://127.0.0.1:2480"
            - "--initial-cluster=metastore-business-etcd=http://127.0.0.1:2480"
            - "--initial-cluster-state=new"
  volumeClaimTemplates:
    - metadata:
        name: metastore-business-etcd
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
