name: Dataflow Engine Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:
    tag:
    description: 'docker image tag'
    required: true
    default: ''


# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docker:
    name: Push To Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: amyangfei
          password: ${{ secrets.DOCKERHUB }}

      - name: Get Tag Name
        id: imageTag
        env:
          INPUT_IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          if [[ -z "$INPUT_IMAGE_TAG" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=${INPUT_IMAGE_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          file: deployments/engine/docker/Dockerfile
          push: true
          tags: amyangfei/tiflow:${{ steps.imageTag.outputs.tag }}
