name: integration-tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Avro-integration:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/integration
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/integration
          ./integration

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/docker/logs/*

      - name: Clean Up
        run: |
          $GITHUB_WORKSPACE/scripts/avro-local-test.sh down

  Canal-integration:
    needs: [Avro-integration]
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/integration
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/integration
          ./integration -protocol=canal

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/docker/logs/*

      - name: Clean Up
        run: |
          $GITHUB_WORKSPACE/scripts/canal/canal-local-test.sh down

