name: CDC Integration Tests Cron

on:
  schedule:
    - cron: '0 17-23 * * *' # run at minute 0 every hour from 01:00 ~ 07:00 UTC+8

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Canal-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          docker volume prune -f
          docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-canal.yml pull --ignore-pull-failures

      - name: TiDB version
        run: |
          docker run pingcap/tidb:nightly -V
          docker run pingcap/tikv:nightly -V
          docker run pingcap/pd:nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          ./mq_protocol_tests -protocol=canal

      - name: Try to dump container logs
        if: ${{ failure() }}
        run: docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-canal.yml logs -t

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/deployments/ticdc/docker-compose/logs/*

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/canal/canal-local-test.sh down

  Avro-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          docker volume prune -f
          docker image prune -f
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-cdc-integration-vendor-${{ hashFiles('go.sum') }}

      - name: Update Vendor
        run: go mod vendor

      - name: Pull images
        run: docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-avro.yml pull --ignore-pull-failures

      - name: TiDB version
        run: |
          docker run pingcap/tidb:nightly -V
          docker run pingcap/tikv:nightly -V
          docker run pingcap/pd:nightly -V

      - name: Build Integration Framework
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          go build

      - name: Run Integration Framework
        timeout-minutes: 45
        run: |
          cd $GITHUB_WORKSPACE/tests/mq_protocol_tests
          ./mq_protocol_tests

      - name: Try to dump container logs
        if: ${{ failure() }}
        run: docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-avro.yml logs -t

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: ${{ github.workspace }}/deployments/ticdc/docker-compose/logs/*

      - name: Clean Up
        if: ${{ always() }}
        run: |
          $GITHUB_WORKSPACE/scripts/avro-local-test.sh down
